services: 
  db: 
    image: postgres
    container_name: db
    restart: always
    ports:
      - 4457:5432
    env_file:
      - back-end/.env
    volumes:
      - pg:/var/lib/postgresql/data
  
  node_app:
    container_name: node_app
    build: ./back-end
    ports: 
      - 5000:5000
    depends_on:
      - db
    env_file:
      - back-end/.env 
  
  app_react:
    container_name: app_react
    build: ./front-end
    image: app_react_image
    volumes:
      - build_react:/var/www/html

  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx_image
    ports:
      - 8080:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - db
      - node_app
      - app_react

volumes:
  pg:
  build_react: